In [1]:
import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
from matplotlib import rc
import missingno as msno

In [5]:
#테스트 데이터 추출 80%
data = pd.read_csv('./data/train_data.csv')

In [6]:
data

,td,code,F001,F002,F003,F004,F005,F006,F007,F008,...,F037,F038,F039,F040,F041,F042,F043,F044,F045,F046
0,T001,A005,7.267364,0.004896,0.945559,-0.828748,0.641026,-0.038719,0.015282,-1.015634,...,-1.567398,0.007646,0.002793,1.0,0.004724,-1.041667,13.357401,0.793424,11.347518,0.544470
1,T001,A006,-7.477904,-0.000128,1.089255,0.042335,7.640449,0.038965,0.016616,-0.631765,...,-1.033058,-0.001463,-0.002713,2.0,-0.004431,2.040816,-14.464286,0.546866,-4.960317,3.914780
2,T001,A007,7.622525,0.001413,1.260723,0.001667,13.735577,0.025740,0.012530,6.140861,...,7.648485,0.003168,-0.000951,6.0,-0.004544,0.000000,13.052749,0.523903,-1.228115,9.910044
3,T001,A011,51.693204,0.000000,6.967351,0.268144,-11.543311,0.143675,0.033834,0.401105,...,1.358087,0.037001,-0.004078,2.0,0.012924,-7.142857,156.242771,1.050259,137.679277,-2.979930
4,T001,A012,-7.707446,-0.000763,1.201887,0.285988,21.070234,-0.006894,0.017134,0.497051,...,0.835655,-0.059726,-0.000538,5.0,-0.000045,0.000000,-17.351598,0.865144,-17.539863,12.087614
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83559,T274,A791,5.411604,0.000000,0.560828,-0.101983,-8.063605,0.029134,0.026586,-6.890195,...,-18.278760,-0.000252,-0.009729,4.0,-0.007442,-22.693267,14.001306,1.637208,1.333598,-3.507891
83560,T274,A793,82.562142,0.000000,8.971392,-0.008897,22.222222,0.206389,0.033859,19.184370,...,64.794007,0.021994,-0.004664,2.0,0.111940,0.000000,275.426621,1.005348,158.823529,8.893188
83561,T274,A794,0.186385,0.000893,2.374996,-0.052632,25.110132,0.029708,0.030444,9.984827,...,30.275229,0.093428,0.000383,5.0,-0.020436,13.725490,0.530973,0.872873,43.434343,6.393844
83562,T274,A795,-5.515355,-0.005224,4.898941,-0.037037,6.101190,0.097354,0.023531,-0.481948,...,-1.109570,0.031893,-0.009076,2.0,-0.009050,-4.255319,-12.083847,0.880508,-1.246537,3.634898
83563,T274,A796,3.056981,-0.005908,2.252730,-0.035714,-17.596567,0.140226,0.035148,-6.005738,...,-20.661157,-0.003084,-0.005149,2.0,0.054743,0.000000,9.090909,1.280150,11.953353,-5.925237

In [7]:
data_80 = data.drop(data.index[66750:])

In [8]:
data_80

,td,code,F001,F002,F003,F004,F005,F006,F007,F008,...,F037,F038,F039,F040,F041,F042,F043,F044,F045,F046
0,T001,A005,7.267364,0.004896,0.945559,-0.828748,0.641026,-0.038719,0.015282,-1.015634,...,-1.567398,0.007646,0.002793,1.0,0.004724,-1.041667,13.357401,0.793424,11.347518,0.544470
1,T001,A006,-7.477904,-0.000128,1.089255,0.042335,7.640449,0.038965,0.016616,-0.631765,...,-1.033058,-0.001463,-0.002713,2.0,-0.004431,2.040816,-14.464286,0.546866,-4.960317,3.914780
2,T001,A007,7.622525,0.001413,1.260723,0.001667,13.735577,0.025740,0.012530,6.140861,...,7.648485,0.003168,-0.000951,6.0,-0.004544,0.000000,13.052749,0.523903,-1.228115,9.910044
3,T001,A011,51.693204,0.000000,6.967351,0.268144,-11.543311,0.143675,0.033834,0.401105,...,1.358087,0.037001,-0.004078,2.0,0.012924,-7.142857,156.242771,1.050259,137.679277,-2.979930
4,T001,A012,-7.707446,-0.000763,1.201887,0.285988,21.070234,-0.006894,0.017134,0.497051,...,0.835655,-0.059726,-0.000538,5.0,-0.000045,0.000000,-17.351598,0.865144,-17.539863,12.087614
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66745,T221,A791,3.207591,-0.000426,0.498096,0.000000,9.132185,0.020778,0.022043,13.745443,...,29.800654,0.014053,0.002577,4.0,0.006425,17.934783,7.338857,0.872475,19.222646,3.298909
66746,T221,A792,-7.215594,0.006063,1.499749,0.007088,1.812689,0.081589,0.013756,8.872832,...,12.333333,-0.021775,0.004787,2.0,0.006967,0.000000,-13.144330,0.788257,-9.164420,1.621950
66747,T221,A794,-4.276021,0.000000,2.367161,0.000000,0.751880,0.008257,0.023889,5.247344,...,12.368973,-0.071715,-0.009429,5.0,0.003697,1.818182,-9.612142,1.005861,2.485660,0.227016
66748,T221,A795,-12.036984,0.002459,4.287941,-0.022989,-1.045752,0.084706,0.024541,6.367991,...,15.396341,0.015367,0.004761,2.0,0.030309,1.941748,-28.920188,1.016350,-25.049505,-0.365337
66749,T221,A796,NaN,0.006775,2.703225,0.302104,21.383648,0.200835,0.022659,13.184400,...,29.530201,0.109777,0.093003,2.0,0.105813,NaN,0.000000,0.923883,0.000000,9.074693

In [10]:
data_80.describe()

,F001,F002,F003,F004,F005,F006,F007,F008,F009,F010,...,F037,F038,F039,F040,F041,F042,F043,F044,F045,F046
count,64249.000000,58175.000000,65535.000000,66645.000000,66645.000000,55660.000000,66121.000000,65992.000000,57044.000000,56777.000000,...,66645.000000,64492.000000,56940.000000,66633.000000,56134.000000,54099.000000,66645.000000,66750.000000,66645.000000,66419.000000
mean,7.487050,0.000909,3.222144,0.214629,1.732157,0.051956,0.024672,1.380114,0.909255,-0.000140,...,5.016430,0.001985,0.001428,3.762670,0.002534,0.439288,23.389390,1.001565,16.662048,0.387115
std,22.697695,0.042506,18.941785,1.985214,14.315450,0.071553,0.010688,8.310774,0.602650,0.017544,...,29.024719,0.365628,0.026182,1.983244,0.036149,8.666515,79.438446,0.269905,62.696423,4.639153
min,-42.528622,-3.832419,0.169382,-76.840000,-59.385189,-0.866186,0.005690,-25.205660,-0.012207,-0.225704,...,-70.219780,-43.672986,-0.727923,1.000000,-0.727923,-92.500000,-92.017722,0.101138,-89.843290,-27.129616
25%,-6.622243,-0.001275,0.916133,-0.020606,-5.829596,0.019506,0.018053,-4.410363,0.446429,-0.001902,...,-9.439124,-0.007150,-0.003021,2.000000,-0.006046,-1.492537,-13.772455,0.870232,-12.957746,-2.842660
50%,2.516390,0.000000,1.537018,0.000000,0.233764,0.041746,0.022649,0.483826,0.800000,-0.000011,...,0.854701,0.002050,0.000000,4.000000,-0.000110,0.000000,3.846154,0.989233,2.800326,0.126433
75%,15.515853,0.000336,3.007508,0.065530,7.387387,0.071924,0.028649,6.134676,1.234568,0.001308,...,13.720930,0.014320,0.002477,5.000000,0.006895,1.724138,36.363636,1.102743,28.837877,3.361250
max,470.723992,4.133958,983.606913,345.800000,691.925065,1.670955,0.383430,109.968661,9.090909,2.307626,...,1563.043478,5.317080,1.160028,7.000000,1.160612,207.692308,3125.524476,21.820324,2900.000000,56.845020

In [13]:

col_43 = data_80.loc['F043']

KeyError: 'F043'

In [17]:
col_43 = data_80['F043']

In [20]:
col_43.describe()

count    66645.000000
mean        23.389390
std         79.438446
min        -92.017722
25%        -13.772455
50%          3.846154
75%         36.363636
max       3125.524476
Name: F043, dtype: float64

In [21]:
col_43.mean()

23.389389883529084

In [22]:
col_43.mean()-4*col_43.std()

-294.3643957135181

In [23]:
[col_43.mean()-4*col_43.std(), col_43.mean()+4*col_43.std()]

[-294.3643957135181, 341.14317548057625]

In [48]:
(col_43.mean()-4*col_43.std() < col_43) & (col_43 > col_43.mean()+4*col_43.std())

0        False
1        False
2        False
3        False
4        False
         ...
66745    False
66746    False
66747    False
66748    False
66749    False
Name: F043, Length: 66750, dtype: bool

In [62]:
col_43_outlier = col_43[(col_43.mean()-4*col_43.std() < col_43) & (col_43 > col_43.mean()+4*col_43.std())]
col_43_outlier.head()
col_43_outlier

3176     343.097643
3936     368.965517
4231     539.240506
4526     541.791045
4824     491.133005
            ...
63297    438.318912
63401    673.937583
63553    413.245033
63696    667.345553
63843    358.781362
Name: F043, Length: 518, dtype: float64

In [65]:
col_43_outlier[:] = col_43.mean()
col_43_outlier.head()

3176    23.38939
3936    23.38939
4231    23.38939
4526    23.38939
4824    23.38939
Name: F043, dtype: float64

In [66]:
col_43_outlier

3176     23.38939
3936     23.38939
4231     23.38939
4526     23.38939
4824     23.38939
           ...
63297    23.38939
63401    23.38939
63553    23.38939
63696    23.38939
63843    23.38939
Name: F043, Length: 518, dtype: float64

In [67]:
col_43

0         13.357401
1        -14.464286
2         13.052749
3        156.242771
4        -17.351598
            ...
66745      7.338857
66746    -13.144330
66747     -9.612142
66748    -28.920188
66749      0.000000
Name: F043, Length: 66750, dtype: float64

In [70]:
col_43_outlier[:] = col_43.mean()
col_43_outlier

3176     23.38939
3936     23.38939
4231     23.38939
4526     23.38939
4824     23.38939
           ...
63297    23.38939
63401    23.38939
63553    23.38939
63696    23.38939
63843    23.38939
Name: F043, Length: 518, dtype: float64

In [73]:
col_43[:]

0         13.357401
1        -14.464286
2         13.052749
3        156.242771
4        -17.351598
            ...
66745      7.338857
66746    -13.144330
66747     -9.612142
66748    -28.920188
66749      0.000000
Name: F043, Length: 66750, dtype: float64

In [74]:
if col_43[:] = col_43_outlier :
    col_43 = col_43.mean()

SyntaxError: invalid syntax (<ipython-input-74-8be6e6a0a726>, line 1)

In [75]:
print(col_43)

0         13.357401
1        -14.464286
2         13.052749
3        156.242771
4        -17.351598
            ...
66745      7.338857
66746    -13.144330
66747     -9.612142
66748    -28.920188
66749      0.000000
Name: F043, Length: 66750, dtype: float64

In [76]:
D = {col_43[(col_43.mean()-4*col_43.std() < col_43) & (col_43 > col_43.mean()+4*col_43.std())] : col_43.mean()}

TypeError: 'Series' objects are mutable, thus they cannot be hashed

In [ ]:
def f(x):
    return pd.Series()